version: '2.0'

services:
  zookeeper-server:
    image: bitnami/zookeeper:latest
    container_name: zookeeper-server
    hostname: zookeeper-server
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-server-volume:/bitnami/zookeeper
    network_mode: host
  kafka-broker:
    image: bitnami/kafka:latest 
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
    volumes:
      - kafka-broker-volume:/bitnami/kafka
    network_mode: host
    depends_on:
      - zookeeper-server

  kafka-broker-2:
    image: bitnami/kafka:latest 
    container_name: kafka-broker-2
    hostname: kafka-broker-2
    ports:
      - 9093:9093
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-2:9093
    volumes:
      - kafka-broker-volume-2:/bitnami/kafka
    network_mode: host
    depends_on:
      - zookeeper-server

  kafka-broker-3:
    image: bitnami/kafka:latest 
    container_name: kafka-broker-3
    hostname: kafka-broker-3
    ports:
      - 9094:9094
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker-3:9094
    volumes:
      - kafka-broker-volume-3:/bitnami/kafka
    network_mode: host
    depends_on:
      - zookeeper-server

volumes:
  zookeeper-server-volume:
  kafka-broker-volume:
  kafka-broker-volume-2:
  kafka-broker-volume-3:

