spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: kafka-broker:9092,kafka-broker-2:9093,kafka-broker-3:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  admin:
    properties:
      bootstrap-servers: kafka-broker:9092,kafka-broker-2:9093,kafka-broker-3:9094
